version: '3.8'

services:
  auth_service:
    build: ./auth_service
    ports:
      - "8000:8000"
    env_file:
      - ./auth_service/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appka_network

  ai_service:
    build: ./ai_service
    ports:
      - "8001:8001"
    env_file:
      - ./ai_service/.env
    volumes:
      - ./ai_service/prompt.txt:/app/ai_service/prompt.txt
    networks:
      - appka_network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appka
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appka_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appka"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  postgres_data:

networks:
  appka_network:
    driver: bridge 